# fly.toml app configuration file generated for porchfest-nav on 2026-05-11T09:59:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'porchfest-nav'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  OSM_REGION_NAME = 'region'
  OSRM_PROFILES = 'foot,bike'
  OSM_BBOX = '-75.2501227279,39.9311022072,-75.1754357155,39.9720779568'

[[mounts]]
  source = 'osrm_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 300
    soft_limit = 200

  [[services.http_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '3m0s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
